[package]
name = "wasm"
version = "0.1.0"
authors = ["Stewart Tootill <stewart.tootill@live.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.4"
anyhow = "1.0"
generic-array = "0.13"
